import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="text-center bg-yellow-500 h-5 w-full">
          This is a Root Header
        </header>
        <main>{children}</main>
        <footer className="text-center bg-red-500 text-white h-5 w-full">
          This is a Root footer
        </footer>
      </body>
    </html>
  );
}
